import type {
  FavelaServiceDefinitionSummary,
  FrontStoreKindTemplateSummary,
  GpTemplateSummary,
  PropertyDefinitionSummary,
} from '../types.js';
import {
  INVENTORY_HOUSE_BONUS_SLOTS,
  INVENTORY_HOUSE_BONUS_WEIGHT,
} from './core.js';

export const FAVELA_SERVICE_OPERATION_CYCLE_MINUTES = 360;
export const BOCA_OPERATION_CYCLE_MINUTES = 60;
export const RAVE_OPERATION_CYCLE_MINUTES = 90;
export const PUTEIRO_OPERATION_CYCLE_MINUTES = 180;
export const PUTEIRO_MAX_ACTIVE_GPS = 5;
export const PUTEIRO_DST_RECOVERY_CYCLES = 4;
export const FRONT_STORE_OPERATION_CYCLE_MINUTES = 240;
export const FRONT_STORE_LAUNDERING_DURATION_HOURS = 6;
export const FRONT_STORE_INVESTIGATION_BLOCK_HOURS = 12;
export const SLOT_MACHINE_OPERATION_CYCLE_MINUTES = 240;
export const SLOT_MACHINE_INSTALL_COST = 5000;
export const SLOT_MACHINE_DEFAULT_HOUSE_EDGE = 0.22;
export const SLOT_MACHINE_MIN_HOUSE_EDGE = 0.15;
export const SLOT_MACHINE_MAX_HOUSE_EDGE = 0.3;
export const SLOT_MACHINE_DEFAULT_JACKPOT_CHANCE = 0.01;
export const SLOT_MACHINE_MIN_JACKPOT_CHANCE = 0.005;
export const SLOT_MACHINE_MAX_JACKPOT_CHANCE = 0.02;
export const SLOT_MACHINE_MIN_BET = 100;
export const SLOT_MACHINE_MAX_BET = 100000;
export const SLOT_MACHINE_DEFAULT_MIN_BET = 100;
export const SLOT_MACHINE_DEFAULT_MAX_BET = 1000;
export const BICHO_DRAW_INTERVAL_MINUTES = 30;
export const BICHO_MIN_BET = 100;
export const BICHO_MAX_BET = 100000;
export const BICHO_PAYOUT_MULTIPLIERS = {
  cabeca: 18,
  dezena: 60,
  grupo: 5,
} as const;
export const RAVE_DEFAULT_PRICE_MULTIPLIER = 1.55;
export const RAVE_MAX_PRICE_MULTIPLIER = 2.8;
export const RAVE_MIN_PRICE_MULTIPLIER = 1.1;
export const PROPERTY_DOMINATION_TIER_THRESHOLDS = {
  absolute: 1,
  dominant: 0.75,
  none: 0,
  partial: 0.25,
  strong: 0.5,
} as const;

export const FAVELA_SERVICE_DEFINITIONS: FavelaServiceDefinitionSummary[] = [
  {
    baseDailyRevenuePerResident: 500,
    installCost: 50000,
    label: 'GatoNet',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'gatonet',
    upgradeRevenueStepMultiplier: 0.4,
  },
  {
    baseDailyRevenuePerResident: 300,
    installCost: 30000,
    label: 'TV Gato',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'tvgato',
    upgradeRevenueStepMultiplier: 0.4,
  },
  {
    baseDailyRevenuePerResident: 400,
    installCost: 40000,
    label: 'Botijao de Gas',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'botijao_gas',
    upgradeRevenueStepMultiplier: 0.4,
  },
  {
    baseDailyRevenuePerResident: 350,
    installCost: 35000,
    label: 'Mototaxi',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'mototaxi',
    upgradeRevenueStepMultiplier: 0.4,
  },
  {
    baseDailyRevenuePerResident: 450,
    installCost: 45000,
    label: 'Van',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'van',
    upgradeRevenueStepMultiplier: 0.4,
  },
  {
    baseDailyRevenuePerResident: 600,
    installCost: 60000,
    label: 'Comercio Local',
    maxLevel: 3,
    satisfactionGainOnUpgrade: 5,
    type: 'comercio_local',
    upgradeRevenueStepMultiplier: 0.4,
  },
] as const;

export const PROPERTY_DEFINITIONS: PropertyDefinitionSummary[] = [
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 150,
    basePrice: 5000,
    baseProtectionScore: 40,
    category: 'realty',
    factionCommissionRate: 0,
    label: 'Casa',
    maxLevel: 3,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 4,
    stockAvailable: null,
    type: 'house',
    unlockLevel: 1,
    utility: {
      inventorySlotsBonus: INVENTORY_HOUSE_BONUS_SLOTS,
      inventoryWeightBonus: INVENTORY_HOUSE_BONUS_WEIGHT,
      cansacoRecoveryPerHourBonus: 2,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 9000,
    baseDailyMaintenanceCost: 600,
    basePrice: 25000,
    baseProtectionScore: 55,
    category: 'business',
    factionCommissionRate: 0.12,
    label: 'Boca de Fumo',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'direct',
    soldierCapacity: 10,
    stockAvailable: null,
    type: 'boca',
    unlockLevel: 4,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 15000,
    baseDailyMaintenanceCost: 1200,
    basePrice: 40000,
    baseProtectionScore: 60,
    category: 'business',
    factionCommissionRate: 0.1,
    label: 'Rave / Baile',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'direct',
    soldierCapacity: 8,
    stockAvailable: null,
    type: 'rave',
    unlockLevel: 4,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 18000,
    baseDailyMaintenanceCost: 1800,
    basePrice: 75000,
    baseProtectionScore: 70,
    category: 'business',
    factionCommissionRate: 0.1,
    label: 'Puteiro',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'direct',
    soldierCapacity: 10,
    stockAvailable: null,
    type: 'puteiro',
    unlockLevel: 6,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 7000,
    baseDailyMaintenanceCost: 900,
    basePrice: 50000,
    baseProtectionScore: 52,
    category: 'business',
    factionCommissionRate: 0.06,
    label: 'Loja de Fachada',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'direct',
    soldierCapacity: 6,
    stockAvailable: null,
    type: 'front_store',
    unlockLevel: 6,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 5000,
    baseDailyMaintenanceCost: 450,
    basePrice: 30000,
    baseProtectionScore: 48,
    category: 'business',
    factionCommissionRate: 0.07,
    label: 'Maquininha de Caca-Niquel',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'direct',
    soldierCapacity: 4,
    stockAvailable: null,
    type: 'slot_machine',
    unlockLevel: 5,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 12000,
    baseDailyMaintenanceCost: 0,
    basePrice: 0,
    baseProtectionScore: 65,
    category: 'business',
    factionCommissionRate: 0.08,
    label: 'Fabrica',
    maxLevel: 3,
    profitable: true,
    purchaseMode: 'specialized',
    soldierCapacity: 8,
    stockAvailable: null,
    type: 'factory',
    unlockLevel: 3,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 480,
    basePrice: 85000,
    baseProtectionScore: 50,
    category: 'realty',
    factionCommissionRate: 0,
    label: 'Casa de Praia',
    maxLevel: 3,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 4,
    stockAvailable: null,
    type: 'beach_house',
    unlockLevel: 4,
    utility: {
      inventorySlotsBonus: 8,
      inventoryWeightBonus: 24,
      cansacoRecoveryPerHourBonus: 3,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 1600,
    basePrice: 250000,
    baseProtectionScore: 78,
    category: 'realty',
    factionCommissionRate: 0,
    label: 'Mansao',
    maxLevel: 3,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 8,
    stockAvailable: null,
    type: 'mansion',
    unlockLevel: 7,
    utility: {
      inventorySlotsBonus: 12,
      inventoryWeightBonus: 36,
      cansacoRecoveryPerHourBonus: 4,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 18000,
    baseProtectionScore: 18,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Carro',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'car',
    unlockLevel: 2,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'ground',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 70000,
    baseProtectionScore: 28,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Barco',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'boat',
    unlockLevel: 4,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'sea',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 450000,
    baseProtectionScore: 58,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Iate',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 2,
    stockAvailable: null,
    type: 'yacht',
    unlockLevel: 8,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'sea',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 40000,
    baseProtectionScore: 16,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Jet Ski',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'jet_ski',
    unlockLevel: 3,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'sea',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 600000,
    baseProtectionScore: 34,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Aviao',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'airplane',
    unlockLevel: 9,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'air',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 420000,
    baseProtectionScore: 32,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Helicoptero',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'helicopter',
    unlockLevel: 8,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: 'air',
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 55000,
    baseProtectionScore: 20,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Joias',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'jewelry',
    unlockLevel: 3,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
  {
    baseDailyIncome: 0,
    baseDailyMaintenanceCost: 0,
    basePrice: 180000,
    baseProtectionScore: 26,
    category: 'luxury_item',
    factionCommissionRate: 0,
    label: 'Arte',
    maxLevel: 1,
    profitable: false,
    purchaseMode: 'direct',
    soldierCapacity: 0,
    stockAvailable: null,
    type: 'art',
    unlockLevel: 6,
    utility: {
      inventorySlotsBonus: 0,
      inventoryWeightBonus: 0,
      cansacoRecoveryPerHourBonus: 0,
      travelMode: null,
    },
  },
] as const;

export const GP_TEMPLATES: GpTemplateSummary[] = [
  {
    baseDailyRevenue: 2000,
    label: 'Novinha',
    purchasePrice: 10000,
    cansacoRestorePercent: 10,
    type: 'novinha',
  },
  {
    baseDailyRevenue: 5000,
    label: 'Experiente',
    purchasePrice: 30000,
    cansacoRestorePercent: 12,
    type: 'experiente',
  },
  {
    baseDailyRevenue: 12000,
    label: 'Premium',
    purchasePrice: 80000,
    cansacoRestorePercent: 15,
    type: 'premium',
  },
  {
    baseDailyRevenue: 25000,
    label: 'VIP',
    purchasePrice: 200000,
    cansacoRestorePercent: 18,
    type: 'vip',
  },
  {
    baseDailyRevenue: 50000,
    label: 'Diamante',
    purchasePrice: 500000,
    cansacoRestorePercent: 20,
    type: 'diamante',
  },
] as const;

export const FRONT_STORE_KIND_TEMPLATES: FrontStoreKindTemplateSummary[] = [
  {
    baseDailyLegitRevenue: 1800,
    baseInvestigationRisk: 0.11,
    baseLaunderingCapacityPerDay: 26000,
    cleanReturnMultiplier: 1.07,
    kind: 'lava_rapido',
    label: 'Lava-Rapido',
  },
  {
    baseDailyLegitRevenue: 1300,
    baseInvestigationRisk: 0.08,
    baseLaunderingCapacityPerDay: 18000,
    cleanReturnMultiplier: 1.05,
    kind: 'barbearia',
    label: 'Barbearia',
  },
  {
    baseDailyLegitRevenue: 900,
    baseInvestigationRisk: 0.05,
    baseLaunderingCapacityPerDay: 22000,
    cleanReturnMultiplier: 1.04,
    kind: 'igreja',
    label: 'Igreja',
  },
  {
    baseDailyLegitRevenue: 1500,
    baseInvestigationRisk: 0.09,
    baseLaunderingCapacityPerDay: 21000,
    cleanReturnMultiplier: 1.06,
    kind: 'acai',
    label: 'Loja de Acai',
  },
  {
    baseDailyLegitRevenue: 2100,
    baseInvestigationRisk: 0.13,
    baseLaunderingCapacityPerDay: 30000,
    cleanReturnMultiplier: 1.08,
    kind: 'oficina',
    label: 'Oficina Mecanica',
  },
] as const;
