import {
  type FactionUpgradeDefinitionSummary,
  type FactionUpgradeEffectsProfile,
  type SoldierTemplateSummary,
  type TribunalCaseDefinitionSummary,
  type TribunalPunishment,
  type UniversityCourseDefinitionSummary,
  type UniversityPassiveProfile,
  VocationType,
} from '../types.js';

export const UNIVERSITY_EMPTY_PASSIVE_PROFILE: UniversityPassiveProfile = {
  business: {
    bocaDemandMultiplier: 1,
    gpRevenueMultiplier: 1,
    launderingReturnMultiplier: 1,
    passiveRevenueMultiplier: 1,
    propertyMaintenanceMultiplier: 1,
  },
  crime: {
    arrestChanceMultiplier: 1,
    lowLevelSoloRewardMultiplier: 1,
    revealsTargetValue: false,
    soloSuccessMultiplier: 1,
  },
  factory: {
    extraDrugSlots: 0,
    productionMultiplier: 1,
  },
  faction: {
    factionCharismaAura: 0,
  },
  market: {
    feeRate: 0.05,
  },
  police: {
    bribeCostMultiplier: 1,
    negotiationSuccessMultiplier: 1,
  },
  social: {
    communityInfluenceMultiplier: 1,
  },
};

export const FACTION_EMPTY_UPGRADE_EFFECTS: FactionUpgradeEffectsProfile = {
  attributeBonusMultiplier: 1,
  canAccessExclusiveArsenal: false,
  hasFortifiedHeadquarters: false,
  muleDeliveryTier: 0,
  soldierCapacityMultiplier: 1,
};

export const FACTION_UPGRADE_DEFINITIONS: FactionUpgradeDefinitionSummary[] = [
  {
    bankMoneyCost: 5000,
    effectSummary: 'Entrega 1.000 unidades de droga a cada 10 dias de jogo.',
    label: 'Mula de Drogas Nível 1',
    pointsCost: 5000,
    prerequisiteUpgradeTypes: [],
    type: 'mula_nivel_1',
  },
  {
    bankMoneyCost: 20000,
    effectSummary: 'Entrega 10.000 unidades de droga a cada 10 dias de jogo.',
    label: 'Mula de Drogas Nível 2',
    pointsCost: 20000,
    prerequisiteUpgradeTypes: ['mula_nivel_1'],
    type: 'mula_nivel_2',
  },
  {
    bankMoneyCost: 100000,
    effectSummary: 'Entrega 100.000 unidades de droga a cada 10 dias de jogo.',
    label: 'Mula de Drogas Nível 3',
    pointsCost: 100000,
    prerequisiteUpgradeTypes: ['mula_nivel_2'],
    type: 'mula_nivel_3',
  },
  {
    bankMoneyCost: 500000,
    effectSummary: 'Entrega 250.000.000 unidades de droga a cada 10 dias de jogo.',
    label: 'Mula de Drogas Nível MAX',
    pointsCost: 500000,
    prerequisiteUpgradeTypes: ['mula_nivel_3'],
    type: 'mula_max',
  },
  {
    bankMoneyCost: 10000,
    effectSummary: '+5% em todos os atributos dos membros da facção.',
    label: 'Bônus de Atributos +5%',
    pointsCost: 10000,
    prerequisiteUpgradeTypes: [],
    type: 'bonus_atributos_5',
  },
  {
    bankMoneyCost: 50000,
    effectSummary: '+10% em todos os atributos dos membros da facção.',
    label: 'Bônus de Atributos +10%',
    pointsCost: 50000,
    prerequisiteUpgradeTypes: ['bonus_atributos_5'],
    type: 'bonus_atributos_10',
  },
  {
    bankMoneyCost: 30000,
    effectSummary: 'Libera acesso ao arsenal exclusivo da facção.',
    label: 'Arsenal Exclusivo',
    pointsCost: 30000,
    prerequisiteUpgradeTypes: [],
    type: 'arsenal_exclusivo',
  },
  {
    bankMoneyCost: 25000,
    effectSummary: '+50% de capacidade de soldados nas propriedades e territórios.',
    label: 'Exército Expandido',
    pointsCost: 25000,
    prerequisiteUpgradeTypes: [],
    type: 'exercito_expandido',
  },
  {
    bankMoneyCost: 40000,
    effectSummary: 'Sede da facção com defesa extra.',
    label: 'QG Fortificado',
    pointsCost: 40000,
    prerequisiteUpgradeTypes: [],
    type: 'qg_fortificado',
  },
] as const;

export const TRIBUNAL_CASE_DEFINITIONS: TribunalCaseDefinitionSummary[] = [
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Roubo entre moradores',
    severity: 'media',
    type: 'roubo_entre_moradores',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Talaricagem',
    severity: 'media',
    type: 'talaricagem',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Divida de jogo',
    severity: 'baixa_media',
    type: 'divida_jogo',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Divida de drogas',
    severity: 'media_alta',
    type: 'divida_drogas',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Estupro',
    severity: 'muito_alta',
    type: 'estupro',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Agressao',
    severity: 'media',
    type: 'agressao',
  },
  {
    allowedPunishments: ['aviso', 'surra', 'expulsao', 'matar', 'esquartejar', 'queimar_no_pneu'],
    label: 'Homicidio nao autorizado',
    severity: 'muito_alta',
    type: 'homicidio_nao_autorizado',
  },
] as const;

export const TRIBUNAL_PUNISHMENT_LABELS: Record<TribunalPunishment, string> = {
  aviso: 'Liberar com aviso',
  surra: 'Dar uma surra',
  expulsao: 'Expulsar da favela',
  matar: 'Matar',
  esquartejar: 'Esquartejar',
  queimar_no_pneu: 'Queimar no pneu',
};

export const UNIVERSITY_COURSE_DEFINITIONS: UniversityCourseDefinitionSummary[] = [
  {
    attributeRequirements: {},
    code: 'mao_leve',
    durationHours: 24,
    effectSummary: '+10% sucesso em crimes solo.',
    label: 'Mao Leve',
    moneyCost: 25000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Cria,
  },
  {
    attributeRequirements: {
      forca: 500,
    },
    code: 'corrida_de_fuga',
    durationHours: 48,
    effectSummary: '-20% chance de prisao em falhas.',
    label: 'Corrida de Fuga',
    moneyCost: 60000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Cria,
  },
  {
    attributeRequirements: {},
    code: 'olho_clinico',
    durationHours: 72,
    effectSummary: 'Revela valor real dos alvos antes do crime.',
    label: 'Olho Clinico',
    moneyCost: 120000,
    prerequisiteCourseCodes: [],
    unlockLevel: 8,
    vocation: VocationType.Cria,
  },
  {
    attributeRequirements: {},
    code: 'rei_da_rua',
    durationHours: 120,
    effectSummary: '+25% recompensa em crimes solo de nivel 1-4.',
    label: 'Rei da Rua',
    moneyCost: 250000,
    prerequisiteCourseCodes: ['mao_leve', 'corrida_de_fuga', 'olho_clinico'],
    unlockLevel: 9,
    vocation: VocationType.Cria,
  },
  {
    attributeRequirements: {},
    code: 'logistica_de_boca',
    durationHours: 24,
    effectSummary: 'Fabricas produzem 15% mais.',
    label: 'Logistica de Boca',
    moneyCost: 25000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Gerente,
  },
  {
    attributeRequirements: {
      inteligencia: 500,
    },
    code: 'rede_de_distribuicao',
    durationHours: 48,
    effectSummary: 'Bocas vendem 20% mais por ciclo.',
    label: 'Rede de Distribuicao',
    moneyCost: 60000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Gerente,
  },
  {
    attributeRequirements: {},
    code: 'quimico_mestre',
    durationHours: 72,
    effectSummary: 'Desbloqueia um segundo slot de producao por fabrica.',
    label: 'Quimico Mestre',
    moneyCost: 120000,
    prerequisiteCourseCodes: [],
    unlockLevel: 8,
    vocation: VocationType.Gerente,
  },
  {
    attributeRequirements: {},
    code: 'magnata_do_po',
    durationHours: 120,
    effectSummary: '+30% em toda producao de drogas.',
    label: 'Magnata do Po',
    moneyCost: 250000,
    prerequisiteCourseCodes: ['logistica_de_boca', 'rede_de_distribuicao', 'quimico_mestre'],
    unlockLevel: 9,
    vocation: VocationType.Gerente,
  },
  {
    attributeRequirements: {},
    code: 'tiro_certeiro',
    durationHours: 24,
    effectSummary: '+15% dano em PvP.',
    label: 'Tiro Certeiro',
    moneyCost: 25000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Soldado,
  },
  {
    attributeRequirements: {
      forca: 500,
    },
    code: 'emboscada_perfeita',
    durationHours: 48,
    effectSummary: '+20% poder em emboscadas.',
    label: 'Emboscada Perfeita',
    moneyCost: 60000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Soldado,
  },
  {
    attributeRequirements: {},
    code: 'instinto_de_sobrevivencia',
    durationHours: 72,
    effectSummary: '-30% dano recebido quando HP < 25%.',
    label: 'Instinto de Sobrevivencia',
    moneyCost: 120000,
    prerequisiteCourseCodes: [],
    unlockLevel: 8,
    vocation: VocationType.Soldado,
  },
  {
    attributeRequirements: {},
    code: 'maquina_de_guerra',
    durationHours: 120,
    effectSummary: '+25% em Poder de Assalto total.',
    label: 'Maquina de Guerra',
    moneyCost: 250000,
    prerequisiteCourseCodes: ['tiro_certeiro', 'emboscada_perfeita', 'instinto_de_sobrevivencia'],
    unlockLevel: 9,
    vocation: VocationType.Soldado,
  },
  {
    attributeRequirements: {},
    code: 'labia_de_politico',
    durationHours: 24,
    effectSummary: '+20% sucesso em negociacoes com PM.',
    label: 'Labia de Politico',
    moneyCost: 25000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Politico,
  },
  {
    attributeRequirements: {
      carisma: 500,
    },
    code: 'rede_de_contatos',
    durationHours: 48,
    effectSummary: '+15% lucro com GPs e -20% custo de suborno.',
    label: 'Rede de Contatos',
    moneyCost: 60000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Politico,
  },
  {
    attributeRequirements: {},
    code: 'manipulacao_de_massa',
    durationHours: 72,
    effectSummary: '+25% influencia em satisfacao dos moradores.',
    label: 'Manipulacao de Massa',
    moneyCost: 120000,
    prerequisiteCourseCodes: [],
    unlockLevel: 8,
    vocation: VocationType.Politico,
  },
  {
    attributeRequirements: {},
    code: 'poderoso_chefao',
    durationHours: 120,
    effectSummary: '+5% de carisma para toda a faccao.',
    label: 'Poderoso Chefao',
    moneyCost: 250000,
    prerequisiteCourseCodes: ['labia_de_politico', 'rede_de_contatos', 'manipulacao_de_massa'],
    unlockLevel: 9,
    vocation: VocationType.Politico,
  },
  {
    attributeRequirements: {},
    code: 'engenharia_financeira',
    durationHours: 24,
    effectSummary: '+10% retorno em lavagem de dinheiro.',
    label: 'Engenharia Financeira',
    moneyCost: 25000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Empreendedor,
  },
  {
    attributeRequirements: {
      inteligencia: 500,
    },
    code: 'faro_para_negocios',
    durationHours: 48,
    effectSummary: '-15% custo de manutencao de todas as propriedades.',
    label: 'Faro para Negocios',
    moneyCost: 60000,
    prerequisiteCourseCodes: [],
    unlockLevel: 7,
    vocation: VocationType.Empreendedor,
  },
  {
    attributeRequirements: {},
    code: 'mercado_paralelo',
    durationHours: 72,
    effectSummary: 'Taxa do Mercado Negro reduzida de 5% para 2%.',
    label: 'Mercado Paralelo',
    moneyCost: 120000,
    prerequisiteCourseCodes: [],
    unlockLevel: 8,
    vocation: VocationType.Empreendedor,
  },
  {
    attributeRequirements: {},
    code: 'imperio_do_crime',
    durationHours: 120,
    effectSummary: '+20% renda passiva em todos os negocios.',
    label: 'Imperio do Crime',
    moneyCost: 250000,
    prerequisiteCourseCodes: ['engenharia_financeira', 'faro_para_negocios', 'mercado_paralelo'],
    unlockLevel: 9,
    vocation: VocationType.Empreendedor,
  },
] as const;

export const SOLDIER_TEMPLATES: SoldierTemplateSummary[] = [
  {
    dailyCost: 1000,
    label: 'Olheiro',
    power: 500,
    type: 'olheiro',
    unlockLevel: 3,
  },
  {
    dailyCost: 5000,
    label: 'Soldado de rua',
    power: 2000,
    type: 'soldado_rua',
    unlockLevel: 4,
  },
  {
    dailyCost: 15000,
    label: 'Fogueteiro de alerta',
    power: 5000,
    type: 'fogueteiro_alerta',
    unlockLevel: 5,
  },
  {
    dailyCost: 40000,
    label: 'Seguranca armado',
    power: 10000,
    type: 'seguranca_armado',
    unlockLevel: 7,
  },
  {
    dailyCost: 100000,
    label: 'Mercenario',
    power: 25000,
    type: 'mercenario',
    unlockLevel: 9,
  },
] as const;
