import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  actionCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  actionCopy: {
    gap: 4,
  },
  actionCost: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
  },
  actionLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  actionMeta: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  banner: {
    borderRadius: 16,
    gap: 10,
    padding: 14,
  },
  bannerButton: {
    alignSelf: 'flex-start',
    backgroundColor: colors.text,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  bannerButtonLabel: {
    color: colors.background,
    fontSize: 12,
    fontWeight: '800',
  },
  bannerCopy: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  bannerDanger: {
    backgroundColor: '#3a1717',
    borderColor: '#6a2e2e',
    borderWidth: 1,
  },
  bannerInfo: {
    backgroundColor: '#172233',
    borderColor: '#2c405f',
    borderWidth: 1,
  },
  buttonPressed: {
    opacity: 0.84,
  },
  card: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 20,
    borderWidth: 1,
    gap: 8,
    padding: 16,
  },
  choicePill: {
    alignItems: 'center',
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  choicePillLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  choicePillSelected: {
    backgroundColor: '#2c2417',
    borderColor: colors.accent,
  },
  choiceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  emptyState: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    padding: 16,
  },
  emptyStateCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  fieldLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  helperCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  infoStrip: {
    backgroundColor: '#2e1f15',
    borderColor: '#6b4a2c',
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    padding: 14,
  },
  infoStripCopy: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 18,
  },
  infoStripTitle: {
    color: colors.warning,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  inlineButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  inlineButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  inlineButtonLabel: {
    fontSize: 12,
    fontWeight: '800',
  },
  loadingCard: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 20,
  },
  loadingCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
  },
  loadingTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  mainReason: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 22,
  },
  metaCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 999,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 46,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonContent: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  primaryButtonLabel: {
    color: colors.background,
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 46,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  section: {
    gap: 10,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(7, 9, 13, 0.72)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    borderRadius: 22,
    gap: 14,
    padding: 20,
    width: '100%',
  },
  modalCardDanger: {
    backgroundColor: '#3b1f1f',
    borderColor: 'rgba(220, 102, 102, 0.32)',
    borderWidth: 1,
  },
  modalCardInfo: {
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderWidth: 1,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  modalCopy: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 20,
  },
  summaryCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '48%',
    gap: 2,
    minWidth: 132,
    padding: 14,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 12,
    textTransform: 'uppercase',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '800',
  },
  textInput: {
    backgroundColor: '#151515',
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    color: colors.text,
    marginTop: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  toneLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  toneOption: {
    alignItems: 'center',
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 6,
    minWidth: 84,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  toneOptionSelected: {
    borderColor: colors.accent,
  },
  toneRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
  },
  toneSwatch: {
    borderRadius: 999,
    height: 22,
    width: 22,
  },
});
