import { colors } from '../theme/colors';

export const territoryScreenContentStyles = {
  alertItem: {
    color: colors.warning,
    fontSize: 13,
    lineHeight: 18,
  },
  alertList: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  detailCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  detailCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  detailTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  factorCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flexBasis: '48%',
    gap: 4,
    padding: 12,
  },
  factorList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  factorTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  factorValue: {
    color: colors.info,
    fontSize: 13,
    fontWeight: '700',
  },
  favelaCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '48%',
    gap: 6,
    minHeight: 112,
    padding: 12,
  },
  favelaCardActive: {
    borderColor: colors.accent,
    shadowColor: colors.accent,
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  favelaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  favelaHeader: {
    alignItems: 'flex-start',
    gap: 8,
  },
  favelaMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  favelaTitle: {
    color: colors.text,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  formCard: {
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  formLabel: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  inlineActionCard: {
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 8,
    marginTop: 8,
    padding: 12,
  },
  input: {
    backgroundColor: colors.background,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.text,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  loadingCard: {
    alignItems: 'center',
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    padding: 22,
  },
  loadingCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    maxWidth: 320,
    textAlign: 'center',
  },
  loadingTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  lossBody: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 18,
  },
  lossCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  lossImpact: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  lossList: {
    gap: 10,
  },
  lossMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  lossTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  pressureCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '31%',
    gap: 4,
    padding: 12,
  },
  pressureCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  pressureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  pressureTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  pressureValue: {
    color: colors.warning,
    fontSize: 14,
    fontWeight: '800',
  },
  regionCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '48%',
    gap: 6,
    padding: 14,
  },
  regionCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.panelAlt,
  },
  regionCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  regionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  regionStat: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  regionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  roundCard: {
    backgroundColor: colors.panelAlt,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  roundCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  roundList: {
    gap: 8,
  },
  roundTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  section: {
    gap: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  sectionHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '800',
  },
  serviceCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  serviceCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  serviceHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  serviceHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  serviceSubtitle: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  serviceTitle: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '800',
  },
  summaryCard: {
    backgroundColor: colors.panel,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '48%',
    gap: 6,
    padding: 14,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: '800',
  },
} as const;
