import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  banner: {
    borderRadius: 18,
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  bannerCopy: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 19,
  },
  bannerDanger: {
    backgroundColor: 'rgba(255, 107, 107, 0.16)',
    borderColor: 'rgba(255, 107, 107, 0.26)',
    borderWidth: 1,
  },
  bannerInfo: {
    backgroundColor: 'rgba(91, 164, 255, 0.14)',
    borderColor: 'rgba(91, 164, 255, 0.24)',
    borderWidth: 1,
  },
  buttonPressed: {
    opacity: 0.72,
  },
  card: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  cardBadge: {
    backgroundColor: 'rgba(0,0,0,0.28)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  cardBadgeActive: {
    backgroundColor: 'rgba(240, 179, 46, 0.18)',
    borderColor: 'rgba(240, 179, 46, 0.26)',
  },
  cardBadgeLabel: {
    color: colors.text,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  cardEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  cardHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  cardHeaderCopy: {
    flex: 1,
    gap: 4,
  },
  cardTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 22,
  },
  detailCopy: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 19,
  },
  loadingCard: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    paddingHorizontal: 18,
    paddingVertical: 18,
  },
  loadingCopy: {
    color: colors.muted,
    fontSize: 13,
  },
  listItem: {
    color: colors.text,
    fontSize: 13,
    lineHeight: 20,
  },
  metricLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  metricPill: {
    backgroundColor: 'rgba(0,0,0,0.22)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    gap: 4,
    minWidth: 96,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  metricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  metricValue: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  modalBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.54)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  modalButton: {
    alignItems: 'center',
    backgroundColor: colors.text,
    borderRadius: 14,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  modalButtonLabel: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '800',
  },
  modalCard: {
    borderRadius: 24,
    gap: 14,
    maxWidth: 360,
    paddingHorizontal: 20,
    paddingVertical: 22,
    width: '100%',
  },
  modalCardDanger: {
    backgroundColor: '#3a1919',
    borderColor: 'rgba(255, 107, 107, 0.32)',
    borderWidth: 1,
  },
  modalCardInfo: {
    backgroundColor: '#162537',
    borderColor: 'rgba(91, 164, 255, 0.28)',
    borderWidth: 1,
  },
  modalCopy: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 21,
  },
  modalTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
  },
  optionCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  optionCardCurrent: {
    borderColor: 'rgba(240, 179, 46, 0.28)',
  },
  optionMeta: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700',
  },
  optionWarning: {
    color: colors.warning,
    fontSize: 12,
    lineHeight: 18,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  primaryButtonDisabled: {
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  primaryButtonLabel: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '800',
  },
  primaryButtonLabelDisabled: {
    color: colors.text,
  },
  section: {
    gap: 10,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryButtonLabel: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  summaryCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 20,
    borderWidth: 1,
    flexBasis: '48%',
    flexGrow: 1,
    gap: 8,
    minWidth: 130,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '800',
  },
  topActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
});
