import {
  acUnit,
  awning,
  corrugatedRoof,
  createModuleDefinition,
  externalPipe,
  faceWindow,
  isoPrism,
  sideWall,
  stair,
  waterTank,
} from '../shared/primitives.mjs';

function buildingOneFloor() {
  return [
    isoPrism({
      cx: 92,
      cy: 116,
      width: 46,
      depth: 20,
      height: 24,
      topFill: '#cbbcae',
      leftFill: '#7a675c',
      rightFill: '#8a7669',
    }),
    faceWindow({ x: 88, y: 102, width: 12, height: 10, tilt: 'right' }),
    faceWindow({ x: 72, y: 107, width: 10, height: 9, tilt: 'left', fill: '#7fb1c8' }),
  ].join('');
}

function buildingTwoFloors() {
  return [
    isoPrism({
      cx: 92,
      cy: 118,
      width: 48,
      depth: 20,
      height: 26,
      topFill: '#c9b8aa',
      leftFill: '#776358',
      rightFill: '#887465',
    }),
    isoPrism({
      cx: 100,
      cy: 92,
      width: 40,
      depth: 18,
      height: 24,
      topFill: '#d8ccc1',
      leftFill: '#8a7669',
      rightFill: '#9a8679',
    }),
    faceWindow({ x: 96, y: 77, width: 11, height: 10, tilt: 'right' }),
    faceWindow({ x: 79, y: 101, width: 9, height: 8, tilt: 'left' }),
  ].join('');
}

function buildingThreeFloors() {
  return [
    isoPrism({
      cx: 92,
      cy: 118,
      width: 42,
      depth: 18,
      height: 24,
      topFill: '#c3b0a1',
      leftFill: '#735f54',
      rightFill: '#856f62',
    }),
    isoPrism({
      cx: 98,
      cy: 95,
      width: 38,
      depth: 16,
      height: 22,
      topFill: '#d0c3b6',
      leftFill: '#817063',
      rightFill: '#917d70',
    }),
    isoPrism({
      cx: 104,
      cy: 74,
      width: 32,
      depth: 14,
      height: 20,
      topFill: '#d9cfc7',
      leftFill: '#8a786a',
      rightFill: '#9a8879',
    }),
    faceWindow({ x: 101, y: 60, width: 10, height: 9, tilt: 'right' }),
    faceWindow({ x: 86, y: 83, width: 8, height: 8, tilt: 'left' }),
  ].join('');
}

function narrowBuilding() {
  return [
    isoPrism({
      cx: 94,
      cy: 118,
      width: 30,
      depth: 16,
      height: 34,
      topFill: '#cbbbad',
      leftFill: '#746157',
      rightFill: '#866f63',
    }),
    faceWindow({ x: 92, y: 95, width: 8, height: 9, tilt: 'right' }),
    faceWindow({ x: 82, y: 100, width: 7, height: 7, tilt: 'left' }),
  ].join('');
}

function wideBuilding() {
  return [
    isoPrism({
      cx: 92,
      cy: 118,
      width: 56,
      depth: 22,
      height: 30,
      topFill: '#d1c5bb',
      leftFill: '#7f6a5f',
      rightFill: '#917b6f',
    }),
    faceWindow({ x: 93, y: 96, width: 12, height: 10, tilt: 'right' }),
    faceWindow({ x: 75, y: 102, width: 10, height: 8, tilt: 'left' }),
    awning({ x: 86, y: 105, width: 20 }),
  ].join('');
}

export const favelaModules = [
  createModuleDefinition({
    id: 'building-1f',
    family: 'favela',
    tags: ['favela', 'barraco', 'core-volume'],
    description: 'Bloco base de um pavimento para massas urbanas compactas.',
    footprint: { width: 46, depth: 20 },
    anchor: { x: 92, y: 118 },
    slots: ['facade-front', 'window'],
    variants: { floors: 1 },
    fragment: buildingOneFloor(),
  }),
  createModuleDefinition({
    id: 'building-2f',
    family: 'favela',
    tags: ['favela', 'mid-height', 'core-volume'],
    description: 'Bloco de dois pavimentos para empilhamento irregular.',
    footprint: { width: 48, depth: 20 },
    anchor: { x: 92, y: 118 },
    slots: ['facade-front', 'roof-detail'],
    variants: { floors: 2 },
    fragment: buildingTwoFloors(),
  }),
  createModuleDefinition({
    id: 'building-3f',
    family: 'favela',
    tags: ['favela', 'vertical', 'core-volume'],
    description: 'Bloco de tres pavimentos para silhueta comprimida.',
    footprint: { width: 42, depth: 18 },
    anchor: { x: 92, y: 118 },
    slots: ['facade-front', 'roof-detail'],
    variants: { floors: 3 },
    fragment: buildingThreeFloors(),
  }),
  createModuleDefinition({
    id: 'narrow-building',
    family: 'favela',
    tags: ['favela', 'narrow', 'infill'],
    description: 'Edificacao estreita para miolos adensados.',
    footprint: { width: 30, depth: 16 },
    anchor: { x: 94, y: 118 },
    slots: ['facade-front', 'window'],
    variants: { width: 'narrow' },
    fragment: narrowBuilding(),
  }),
  createModuleDefinition({
    id: 'wide-building',
    family: 'favela',
    tags: ['favela', 'wide', 'anchor'],
    description: 'Edificacao larga para massa dominante lateral.',
    footprint: { width: 56, depth: 22 },
    anchor: { x: 92, y: 118 },
    slots: ['facade-front', 'awning'],
    variants: { width: 'wide' },
    fragment: wideBuilding(),
  }),
  createModuleDefinition({
    id: 'rooftop-slab',
    family: 'favela',
    tags: ['favela', 'roof', 'concrete'],
    description: 'Laje superior plana para leitura de concreto.',
    footprint: { width: 26, depth: 12 },
    anchor: { x: 92, y: 106 },
    slots: ['roof-detail'],
    variants: { roofType: 'slab' },
    fragment: isoPrism({
      cx: 92,
      cy: 108,
      width: 26,
      depth: 12,
      height: 4,
      topFill: '#d8d0c8',
      leftFill: '#94877d',
      rightFill: '#a99c92',
    }),
  }),
  createModuleDefinition({
    id: 'corrugated-roof',
    family: 'favela',
    tags: ['favela', 'roof', 'metal'],
    description: 'Cobertura ondulada metalica para textura urbana.',
    footprint: { width: 34, depth: 16 },
    anchor: { x: 92, y: 104 },
    slots: ['roof-detail'],
    variants: { roofType: 'corrugated' },
    fragment: corrugatedRoof({ x: 92, y: 104 }),
  }),
  createModuleDefinition({
    id: 'water-tank',
    family: 'favela',
    tags: ['favela', 'roof-detail', 'utility'],
    description: 'Caixa dagua ou reservatorio de cobertura.',
    footprint: { width: 14, depth: 10 },
    anchor: { x: 92, y: 104 },
    slots: ['roof-detail'],
    variants: { utility: 'water' },
    fragment: waterTank({ x: 92, y: 102 }),
  }),
  createModuleDefinition({
    id: 'external-pipe',
    family: 'favela',
    tags: ['favela', 'utility', 'facade-detail'],
    description: 'Tubulacao externa para leitura de improviso e servico.',
    footprint: { width: 8, depth: 6 },
    anchor: { x: 92, y: 118 },
    slots: ['utility-side'],
    variants: { utility: 'pipe' },
    fragment: externalPipe({ x: 92, y: 92 }),
  }),
  createModuleDefinition({
    id: 'awning',
    family: 'favela',
    tags: ['favela', 'facade-detail', 'shade'],
    description: 'Toldo de fachada e varanda.',
    footprint: { width: 24, depth: 12 },
    anchor: { x: 92, y: 112 },
    slots: ['facade-front'],
    variants: { facade: 'awning' },
    fragment: awning({ x: 80, y: 98 }),
  }),
  createModuleDefinition({
    id: 'stair',
    family: 'favela',
    tags: ['favela', 'circulation', 'external'],
    description: 'Escada externa para leitura de acesso vertical.',
    footprint: { width: 30, depth: 18 },
    anchor: { x: 86, y: 118 },
    slots: ['circulation'],
    variants: { access: 'external-stair' },
    fragment: stair({ x: 64, y: 94, steps: 5 }),
  }),
  createModuleDefinition({
    id: 'small-window',
    family: 'favela',
    tags: ['favela', 'facade-detail', 'window'],
    description: 'Janela pequena repetivel de fachada.',
    footprint: { width: 14, depth: 8 },
    anchor: { x: 92, y: 104 },
    slots: ['window'],
    variants: { facade: 'window-small' },
    fragment: `${faceWindow({ x: 88, y: 98, width: 10, height: 8, tilt: 'right' })}${faceWindow({ x: 76, y: 103, width: 9, height: 7, tilt: 'left' })}`,
  }),
  createModuleDefinition({
    id: 'ac-unit',
    family: 'favela',
    tags: ['favela', 'facade-detail', 'equipment'],
    description: 'Ar-condicionado ou caixa tecnica lateral.',
    footprint: { width: 16, depth: 8 },
    anchor: { x: 92, y: 104 },
    slots: ['facade-side'],
    variants: { utility: 'ac' },
    fragment: acUnit({ x: 86, y: 98 }),
  }),
  createModuleDefinition({
    id: 'side-wall',
    family: 'favela',
    tags: ['favela', 'facade-detail', 'wall'],
    description: 'Parede lateral cega para encaixe de massa urbana.',
    footprint: { width: 26, depth: 10 },
    anchor: { x: 92, y: 116 },
    slots: ['facade-side'],
    variants: { wall: 'blank' },
    fragment: sideWall({ x: 80, y: 86 }),
  }),
];
