import {
  createModuleDefinition,
  isoPrism,
  corrugatedRoof,
  rooftopSlab,
  waterTank,
  awning,
  externalPipe,
  stair,
  faceWindow,
} from '../shared/primitives.mjs';

function clusterCoreDense() {
  return [
    isoPrism({
      cx: 68,
      cy: 116,
      width: 44,
      depth: 20,
      height: 30,
      topFill: '#b19382',
      leftFill: '#6e5a50',
      rightFill: '#806a5f',
    }),
    isoPrism({
      cx: 96,
      cy: 108,
      width: 46,
      depth: 22,
      height: 44,
      topFill: '#d0c0b2',
      leftFill: '#886f62',
      rightFill: '#9a8274',
    }),
    isoPrism({
      cx: 126,
      cy: 102,
      width: 36,
      depth: 18,
      height: 34,
      topFill: '#c8b29f',
      leftFill: '#7b6358',
      rightFill: '#8d7468',
    }),
    isoPrism({
      cx: 146,
      cy: 95,
      width: 24,
      depth: 14,
      height: 22,
      topFill: '#a69283',
      leftFill: '#68574c',
      rightFill: '#7c695d',
    }),
    corrugatedRoof({ x: 98, y: 62, width: 34, depth: 16, fill: '#807166' }),
    corrugatedRoof({ x: 126, y: 72, width: 26, depth: 12, fill: '#72645a' }),
    waterTank({ x: 71, y: 77 }),
    waterTank({ x: 103, y: 66 }),
    awning({ x: 41, y: 100, width: 24, fill: '#4f7565' }),
    awning({ x: 115, y: 103, width: 18, fill: '#5e6d5f' }),
    externalPipe({ x: 138, y: 80, height: 28 }),
    externalPipe({ x: 56, y: 90, height: 22 }),
    stair({ x: 37, y: 102, steps: 5, fill: '#6d5e54' }),
    faceWindow({ x: 83, y: 80, width: 10, height: 10, tilt: 'right', fill: '#6fa1c5' }),
    faceWindow({ x: 111, y: 83, width: 8, height: 9, tilt: 'right', fill: '#7bb2cf' }),
    faceWindow({ x: 53, y: 93, width: 8, height: 8, tilt: 'left', fill: '#86b7cd' }),
    faceWindow({ x: 137, y: 87, width: 6, height: 8, tilt: 'right', fill: '#89b6c8' }),
  ].join('');
}

function clusterStepLeft() {
  return [
    isoPrism({
      cx: 66,
      cy: 116,
      width: 36,
      depth: 18,
      height: 23,
      topFill: '#b79e8d',
      leftFill: '#6f5c51',
      rightFill: '#826e61',
    }),
    isoPrism({
      cx: 90,
      cy: 108,
      width: 38,
      depth: 18,
      height: 36,
      topFill: '#c6b6ab',
      leftFill: '#7d6c62',
      rightFill: '#907f73',
    }),
    isoPrism({
      cx: 116,
      cy: 98,
      width: 30,
      depth: 16,
      height: 46,
      topFill: '#d2c8bf',
      leftFill: '#857266',
      rightFill: '#978276',
    }),
    rooftopSlab({ x: 116, y: 51, width: 26, depth: 12, fill: '#d7cec6' }),
    corrugatedRoof({ x: 89, y: 76, width: 26, depth: 12, fill: '#7a6c61' }),
    stair({ x: 42, y: 100, steps: 5, fill: '#6a5a50' }),
    waterTank({ x: 94, y: 64 }),
    awning({ x: 63, y: 99, width: 18, fill: '#5b6e62' }),
    faceWindow({ x: 84, y: 84, width: 8, height: 8, tilt: 'right', fill: '#81b1c7' }),
    faceWindow({ x: 107, y: 71, width: 8, height: 9, tilt: 'right', fill: '#89bad4' }),
    faceWindow({ x: 54, y: 98, width: 7, height: 7, tilt: 'left', fill: '#76a5bd' }),
  ].join('');
}

function clusterStepRight() {
  return [
    isoPrism({
      cx: 82,
      cy: 114,
      width: 40,
      depth: 18,
      height: 36,
      topFill: '#d2c0b1',
      leftFill: '#7b685d',
      rightFill: '#907d6f',
    }),
    isoPrism({
      cx: 111,
      cy: 106,
      width: 34,
      depth: 16,
      height: 29,
      topFill: '#c7bbb0',
      leftFill: '#76645a',
      rightFill: '#89766a',
    }),
    isoPrism({
      cx: 138,
      cy: 99,
      width: 26,
      depth: 14,
      height: 21,
      topFill: '#aa9989',
      leftFill: '#67564b',
      rightFill: '#7b695c',
    }),
    corrugatedRoof({ x: 137, y: 77, width: 22, depth: 10, fill: '#7b6d63' }),
    awning({ x: 92, y: 94, width: 18, fill: '#657767' }),
    awning({ x: 122, y: 101, width: 14, fill: '#56685d' }),
    externalPipe({ x: 76, y: 81, height: 24 }),
    waterTank({ x: 102, y: 72 }),
    faceWindow({ x: 84, y: 81, width: 8, height: 9, tilt: 'right', fill: '#85b4cb' }),
    faceWindow({ x: 107, y: 92, width: 7, height: 8, tilt: 'right', fill: '#7aa8c2' }),
    faceWindow({ x: 140, y: 90, width: 6, height: 7, tilt: 'right', fill: '#7aa8c2' }),
  ].join('');
}

function clusterRoofline() {
  return [
    rooftopSlab({ x: 70, y: 95, width: 28, depth: 14, fill: '#d4cbc4' }),
    corrugatedRoof({ x: 96, y: 90, width: 32, depth: 16, fill: '#7f6f63' }),
    rooftopSlab({ x: 122, y: 88, width: 22, depth: 10, fill: '#dad2cb' }),
    corrugatedRoof({ x: 143, y: 92, width: 16, depth: 8, fill: '#76695d' }),
    waterTank({ x: 72, y: 86 }),
    waterTank({ x: 122, y: 80 }),
    externalPipe({ x: 111, y: 86, height: 16 }),
  ].join('');
}

function clusterServiceStrip() {
  return [
    isoPrism({
      cx: 90,
      cy: 115,
      width: 66,
      depth: 20,
      height: 20,
      topFill: '#a99487',
      leftFill: '#65544b',
      rightFill: '#76645a',
    }),
    isoPrism({
      cx: 59,
      cy: 120,
      width: 22,
      depth: 12,
      height: 14,
      topFill: '#9d877b',
      leftFill: '#5e4f47',
      rightFill: '#726057',
    }),
    stair({ x: 49, y: 100, steps: 6, fill: '#65564e' }),
    awning({ x: 86, y: 94, width: 22, fill: '#5e7668' }),
    awning({ x: 108, y: 100, width: 14, fill: '#657161' }),
    externalPipe({ x: 129, y: 94, height: 18 }),
    faceWindow({ x: 79, y: 104, width: 8, height: 8, tilt: 'left', fill: '#86b7cd' }),
    faceWindow({ x: 96, y: 107, width: 8, height: 8, tilt: 'right', fill: '#79aec7' }),
    faceWindow({ x: 115, y: 110, width: 7, height: 7, tilt: 'right', fill: '#7da9bf' }),
  ].join('');
}

export const favelaClusterModules = [
  createModuleDefinition({
    id: 'cluster-core-dense',
    family: 'favela-cluster',
    tags: ['favela-cluster', 'anchor', 'mass'],
    description: 'Nucleo denso de massa urbana para centro de favela.',
    footprint: { width: 84, depth: 34 },
    anchor: { x: 96, y: 118 },
    slots: ['roof-detail', 'utility-top', 'facade-front'],
    variants: { density: 'high' },
    fragment: clusterCoreDense(),
  }),
  createModuleDefinition({
    id: 'cluster-step-left',
    family: 'favela-cluster',
    tags: ['favela-cluster', 'terrace', 'left'],
    description: 'Escalonamento lateral esquerdo para cluster comprimido.',
    footprint: { width: 74, depth: 30 },
    anchor: { x: 94, y: 118 },
    slots: ['roof-detail', 'circulation'],
    variants: { direction: 'left' },
    fragment: clusterStepLeft(),
  }),
  createModuleDefinition({
    id: 'cluster-step-right',
    family: 'favela-cluster',
    tags: ['favela-cluster', 'terrace', 'right'],
    description: 'Escalonamento lateral direito para cluster comprimido.',
    footprint: { width: 70, depth: 28 },
    anchor: { x: 98, y: 118 },
    slots: ['roof-detail', 'utility-side'],
    variants: { direction: 'right' },
    fragment: clusterStepRight(),
  }),
  createModuleDefinition({
    id: 'cluster-roofline',
    family: 'favela-cluster',
    tags: ['favela-cluster', 'roofline', 'utility'],
    description: 'Faixa de coberturas e caixas dagua para fechar a silhueta superior.',
    footprint: { width: 64, depth: 20 },
    anchor: { x: 98, y: 96 },
    slots: ['roof-detail'],
    variants: { role: 'roofline' },
    fragment: clusterRoofline(),
  }),
  createModuleDefinition({
    id: 'cluster-service-strip',
    family: 'favela-cluster',
    tags: ['favela-cluster', 'service', 'street-edge'],
    description: 'Faixa de servico e acesso no pe do cluster.',
    footprint: { width: 72, depth: 20 },
    anchor: { x: 92, y: 118 },
    slots: ['circulation', 'facade-front'],
    variants: { role: 'street-edge' },
    fragment: clusterServiceStrip(),
  }),
];
